### ISSUE TITLE
An unhandler error occured: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by JohanHeyvaert** [SanichKotikov/solid-i18n#1]
Hello,
I'm new to SolidJS so maybe I'm doing something wrong (but I didn't do much!). Trying to use this library by following the basic example :

```
import { createI18n, I18nProvider, Text } from 'solid-i18n';

const i18n = createI18n({ language: 'en' });

function App() {
  return (
    <I18nProvider i18n={i18n}>
      <Text
        message="Read the <link>documentation</link> for more info."
        link={(text) => <a href="https://github.com/SanichKotikov/solid-i18n">{text}</a>}
      />
    </I18nProvider>
  )
}
```

I created a new **SolidStart** project (just the bare template) and added solid-i18n. Then I wrapped the <Html> in the root with the I18Provider just like in the example. Even without adding a <Text> element I am getting this error:
**_An unhandler error occured: SyntaxError: Cannot use import statement outside a module_**

Also, when I start the project, the following warning appears in the console:
_**solid-i18n doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.**_
Maybe the problem is related to this?

**Comment by SanichKotikov** [comment]
Hi. Looks like you need to update your build configuration somehow, or waiting for when I'll find some time to investigate the issue.

P.S. The library works fine for official start guid https://www.solidjs.com/guides/getting-started#try-solid

**Comment by JohanHeyvaert** [comment]
Okay, thanks for your response. In the meantime I've put SolidJS on hold and I'm trying out Svelte. Just comparing different frameworks as we probably want to stop with Angular.
