### ISSUE TITLE
Add Prettier to the project

### ISSUE THREAD

**Issue by RoachxD** [SanichKotikov/solid-i18n#3]
Based on the discussion we had in my recent Pull Request, I would like to suggest adding Prettier to the project. Prettier is an opinionated code formatter that can help maintain a consistent code style and improve readability.

By using Prettier, we can save time and effort in code reviews by automatically formatting our code according to a set of rules. This will also help us avoid unnecessary discussions about code style and focus on more important aspects of the code.

I believe that adding Prettier to the project will be beneficial for all contributors and I would love to hear your thoughts on this.

**Comment by SanichKotikov** [comment]
@RoachxD hi. I'll add Prettier.

**Comment by SanichKotikov** [comment]
Done!

https://github.com/SanichKotikov/solid-i18n/commit/0ec811a17653394197adb07e3b62d63609c9f62d
