### ISSUE TITLE
`MD001/heading-increment/header-increment`: Heading levels should only increment by one level at a time

### ISSUE THREAD

**Issue by RoachxD** [SanichKotikov/solid-i18n#4]
I noticed that some of the headings in the document are not following the `MD001/heading-increment/header-increment` rule. This rule states that heading levels should only increment by one level at a time, for example, from `H2` to `H3`, instead of `H4`. This helps to maintain a clear and consistent structure of the document.

The following lines have headings that violate this rule:

- Line 12 - `H2`
- Lines 21, 40, 49, 68, 78, 96 and 111 - `H4`

I suggest changing the `H4` headings to `H3` headings to comply with the rule. Alternatively, you can add intermediate `H3` headings between the `H2` and `H4` headings to create a logical hierarchy.

**Comment by SanichKotikov** [comment]
For me, there's no difference :) But if you think it's necessary, I don't mind.

**Comment by RoachxD** [comment]
@SanichKotikov I've made a simple PR in regards to this: #6
