### ISSUE TITLE
Add `index.ts` to `components` folder and refactor imports

### ISSUE THREAD

**Issue by RoachxD** [SanichKotikov/solid-i18n#5]
I noticed that the `components` folder does not have an `index.ts` file that exports all the components. This makes importing them in other files more tedious and verbose. I suggest adding an `index.ts` file to the components folder that exports all the components.

Then, we can refactor the libraries `index.ts` file to import from the components folder instead of each individual component file, like this:

```ts
export * from './components';
```

This will simplify the imports and make the code more consistent and maintainable. What do you think?

**Comment by SanichKotikov** [comment]
Sure, thanks!
