### ISSUE TITLE
Where and How to make the translation text for different languages?

### ISSUE THREAD

**Issue by huazhenhz** [SanichKotikov/solid-i18n#8]
The specification is not clear, and I haven't known where and how to make translation text?

Is there any help doumentation?
Thanks a lot!

**Comment by SanichKotikov** [comment]
Hi. Not really sure what exactly you want. There are various localization services on the internet.

- Use solid-i18n in your app
- Use https://www.npmjs.com/package/react-i18n-mini-parser to extract all messages to json.
- Use any localization service to translate messages
- Use translated json in your app, for example https://github.com/SanichKotikov/solid-i18n-example/blob/master/src/i18n.ts#L21

**Comment by huazhenhz** [comment]
Many thanks for your reply!!!
